services:
# web app
  web:  
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices  
      POSTGRES_PORT: 5432
    networks:
      - django-rest  
  # postgres 
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices

    networks:
      - django-rest
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  django-rest:
    driver: bridge

volumes:
  postgres-data:
    driver: local